"""Per-user, idempotent migration from direct launcher shortcuts to bootstrap."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from .core import LAUNCHER_EXE, LauncherStore, _atomic_json, _read_json


@dataclass(frozen=True)
class MigrationResult:
    status: str
    shortcut_target: str
    next_safe_action: str


def migrate_shortcut(
    root: Path, shortcut_record: Path, bootstrap_executable: Path, *, launcher_version: str
) -> MigrationResult:
    """Migrate a portable shortcut record transactionally.

    Installer integration performs the same operation with Windows Shell links;
    this portable representation is intentionally used by diagnostics and CI.
    """
    if not bootstrap_executable.is_file():
        return MigrationResult("BLOCKED", "", "repair bootstrap installation")
    store = LauncherStore(root)
    old = _read_json(shortcut_record)
    if old.get("target") == str(bootstrap_executable):
        return MigrationResult("CURRENT", str(bootstrap_executable), "launch bootstrap")
    launcher = Path(str(old.get("target") or ""))
    if launcher.name != LAUNCHER_EXE or not launcher.is_file():
        return MigrationResult("BLOCKED", "", "repair legacy shortcut target")
    version_dir = store.versions / launcher_version
    try:
        if not version_dir.exists():
            version_dir.mkdir(parents=True)
            shutil.copy2(launcher, version_dir / LAUNCHER_EXE)
            # A direct legacy executable can be preserved but cannot become
            # trusted without the immutable metadata generated by packaging.
            return MigrationResult("BLOCKED", "", "repair legacy launcher metadata before migration")
        metadata = store.validate_installed(version_dir)
        store.write_pointer(store.active_pointer, metadata, version_dir, manifest_digest="legacy-migration")
        store.write_pointer(store.lkg_pointer, metadata, version_dir, manifest_digest="legacy-migration")
        backup = shortcut_record.with_suffix(shortcut_record.suffix + ".pre-bootstrap.json")
        if shortcut_record.exists() and not backup.exists():
            shutil.copy2(shortcut_record, backup)
        _atomic_json(
            shortcut_record,
            {
                "target": str(bootstrap_executable),
                "working_directory": str(bootstrap_executable.parent),
                "target_kind": "bootstrap",
            },
        )
        _atomic_json(
            root / "bootstrap" / "migration_receipt.json",
            {
                "schema_version": 1,
                "status": "MIGRATED",
                "shortcut_backup": str(backup),
                "shortcut_target": str(bootstrap_executable),
                "launcher_version": launcher_version,
            },
        )
        return MigrationResult("MIGRATED", str(bootstrap_executable), "launch bootstrap")
    except Exception as exc:
        return MigrationResult("FAILED_RECOVERABLE", "", f"restore shortcut backup and repair migration: {exc}")
