from __future__ import annotations

import pytest
from PySide6.QtWidgets import QDialog, QSpinBox, QTextEdit

from app.pages.reports import ReportsPage
from tests.ui.helpers import click_button, wait_for_background_tasks

pytestmark = pytest.mark.usability


class _AcceptedWeeklyDialog:
    def __init__(self, parent=None):
        self.week_spin = QSpinBox()
        self.week_spin.setValue(1)
        self.notes_edit = QTextEdit()
        self.notes_edit.setPlainText("Generated by fake usability test.")

    def exec(self):
        return QDialog.DialogCode.Accepted


def test_reports_page_refresh_preview_open_stub_and_weekly_summary(qapp, fake_config, fake_project, captured_open_requests, monkeypatch):
    import app.pages.reports as reports_module

    monkeypatch.setattr(reports_module, "WeeklySummaryDialog", _AcceptedWeeklyDialog)
    page = ReportsPage(fake_config)
    page.show()

    click_button(page, "Refresh")
    assert page.folder_table.rowCount() > 0
    page.folder_table.selectRow(0)
    page.populate_files_for_selected_folder()
    if page.file_list.count():
        page.file_list.setCurrentRow(0)
        assert page.preview.toPlainText()

    click_button(page, "Open Selected Folder")
    assert captured_open_requests
    assert str(fake_project) in str(captured_open_requests[-1])

    click_button(page, "Generate Weekly Summary")
    wait_for_background_tasks()
    assert list((fake_project / "00_Project_Admin" / "Weekly_Status_Reports").glob("Week1_Summary_*.md"))
