from __future__ import annotations

import re

ENTRY_TYPE_FIELD = "Entry Type"
SOURCE_AUDIT_ID_FIELD = "Source Audit ID"
COMPATIBILITY_SOURCE_FIELD = "Compatibility Source"
AUDIT_CONTEXT_FIELD = "Audit Context"
PHYSICAL_AUDIT_VERIFIED_FIELD = "Physical Audit Verified"
COMPATIBILITY_CONFIDENCE_FIELD = "Compatibility Confidence"

ENTRY_TYPE_AUDITED = "Audited"
ENTRY_TYPE_COMPATIBLE = "Compatible"
COMPATIBILITY_SOURCE_PRESS_CAPACITY = "Press Capacity List"

AUDIT_CONTEXT_INSTALLED = "Installed on Machine"
AUDIT_CONTEXT_BENCH = "Not Installed / Bench Audit"
AUDIT_CONTEXT_COMPATIBILITY = "Compatibility row"
AUDIT_CONTEXT_HISTORICAL = "Historical/imported"
AUDIT_CONTEXT_NEEDS_REVIEW = "Needs review"
AUDIT_CONTEXT_VALUES = [
    AUDIT_CONTEXT_INSTALLED,
    AUDIT_CONTEXT_BENCH,
    AUDIT_CONTEXT_COMPATIBILITY,
    AUDIT_CONTEXT_HISTORICAL,
    AUDIT_CONTEXT_NEEDS_REVIEW,
]

VALIDATION_STATUS_PASS = "Pass"
VALIDATION_STATUS_FAIL = "Fail"
VALIDATION_STATUS_WARNING = "Warning"
VALIDATION_STATUS_UNKNOWN = "Unknown"
VALIDATION_STATUS_NOT_OBSERVABLE = "Not Observable"
VALIDATION_STATUS_NOT_APPLICABLE = "Not Applicable"
VALIDATION_STATUS_FOLLOW_UP_REQUIRED = "Follow-up Required"
VALIDATION_STATUS_VALUES = [
    VALIDATION_STATUS_PASS,
    VALIDATION_STATUS_FAIL,
    VALIDATION_STATUS_WARNING,
    VALIDATION_STATUS_UNKNOWN,
    VALIDATION_STATUS_NOT_OBSERVABLE,
    VALIDATION_STATUS_NOT_APPLICABLE,
    VALIDATION_STATUS_FOLLOW_UP_REQUIRED,
]

CYLINDER_COUNT_FIELD = "# of Cylinders"
CYLINDER_TYPE_FIELD = "Cylinder Type"
CYLINDER_TYPE_DEFAULT = "Linear"
CYLINDER_TYPE_VALUES = ["Linear", "Rotary"]
CYLINDER_FIELDS = frozenset({CYLINDER_COUNT_FIELD, CYLINDER_TYPE_FIELD})

AIR_CIRCUIT_ARCHITECTURE_FIELD = "Air Circuit Architecture"
AIR_ARCHITECTURE_ROBOT_ONLY = "Robot Only"
AIR_ARCHITECTURE_EXTERNAL_ONLY = "External Peripheral Only"
AIR_ARCHITECTURE_MIXED = "Mixed Robot + External Peripheral"
AIR_ARCHITECTURE_UNKNOWN = "Unknown / Needs Verification"
AIR_ARCHITECTURE_VALUES = [
    AIR_ARCHITECTURE_ROBOT_ONLY,
    AIR_ARCHITECTURE_EXTERNAL_ONLY,
    AIR_ARCHITECTURE_MIXED,
    AIR_ARCHITECTURE_UNKNOWN,
]

EOAT_VACUUM_CIRCUITS_FIELD = "EOAT Vacuum Circuits"
EOAT_PRESSURE_CIRCUITS_FIELD = "EOAT Pressure Circuits"
EOAT_INTERCHANGEABLE_CIRCUITS_FIELD = "EOAT Interchangeable Circuits"
EOAT_PNEUMATIC_FIELDS = (
    EOAT_VACUUM_CIRCUITS_FIELD,
    EOAT_PRESSURE_CIRCUITS_FIELD,
    EOAT_INTERCHANGEABLE_CIRCUITS_FIELD,
)

ROBOT_VACUUM_CIRCUITS_FIELD = "Robot Vacuum Circuits"
ROBOT_PRESSURE_CIRCUITS_FIELD = "Robot Pressure Circuits"
ROBOT_INTERCHANGEABLE_CIRCUITS_FIELD = "Robot Interchangeable Circuits"
ROBOT_PNEUMATIC_FIELDS = (
    ROBOT_VACUUM_CIRCUITS_FIELD,
    ROBOT_PRESSURE_CIRCUITS_FIELD,
    ROBOT_INTERCHANGEABLE_CIRCUITS_FIELD,
)

EXTERNAL_VACUUM_CIRCUITS_FIELD = "External Vacuum Circuits"
EXTERNAL_PRESSURE_CIRCUITS_FIELD = "External Pressure Circuits"
EXTERNAL_INTERCHANGEABLE_CIRCUITS_FIELD = "External Interchangeable Circuits"
EXTERNAL_PNEUMATIC_FIELDS = (
    EXTERNAL_VACUUM_CIRCUITS_FIELD,
    EXTERNAL_PRESSURE_CIRCUITS_FIELD,
    EXTERNAL_INTERCHANGEABLE_CIRCUITS_FIELD,
)
PNEUMATIC_SOURCE_FIELDS = (*ROBOT_PNEUMATIC_FIELDS, *EXTERNAL_PNEUMATIC_FIELDS)
PNEUMATIC_CIRCUIT_COUNT_FIELDS = (*EOAT_PNEUMATIC_FIELDS, *PNEUMATIC_SOURCE_FIELDS)

MIXED_AIR_CLEANROOM_MACHINES = frozenset({"63", "65", "66", "69"})
MIXED_AIR_CLEANROOM_EOAT_PRESSURE_CIRCUITS = "2"
MIXED_AIR_CLEANROOM_EXTERNAL_PRESSURE_CIRCUITS = "1"
MIXED_AIR_CONTROL_BADGE = "MIXED AIR CONTROL"
EXTERNAL_AIR_CONTROL_NOTE = "External air is controlled through peripheral IO."

MANUAL_COMPLETION_OVERRIDE_FIELD = "Manual Completion Override"
MANUAL_COMPLETION_OVERRIDE_TIMESTAMP_FIELD = "Manual Completion Override Timestamp"
MANUAL_COMPLETION_OVERRIDE_USER_FIELD = "Manual Completion Override User"
IGNORED_EMPTY_FIELDS_AT_OVERRIDE_FIELD = "Ignored Empty Fields At Override"
MANUAL_COMPLETION_OVERRIDE_FIELDS = [
    MANUAL_COMPLETION_OVERRIDE_FIELD,
    MANUAL_COMPLETION_OVERRIDE_TIMESTAMP_FIELD,
    MANUAL_COMPLETION_OVERRIDE_USER_FIELD,
    IGNORED_EMPTY_FIELDS_AT_OVERRIDE_FIELD,
]

COMPATIBILITY_HEADERS = [
    AUDIT_CONTEXT_FIELD,
    ENTRY_TYPE_FIELD,
    SOURCE_AUDIT_ID_FIELD,
    COMPATIBILITY_SOURCE_FIELD,
    PHYSICAL_AUDIT_VERIFIED_FIELD,
    COMPATIBILITY_CONFIDENCE_FIELD,
]

AUTOFILLED_COMPATIBILITY_METADATA_FIELDS = frozenset(
    {
        SOURCE_AUDIT_ID_FIELD,
        COMPATIBILITY_SOURCE_FIELD,
    }
)


def normalize_machine_number(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    if text.endswith(".0"):
        text = text[:-2]
    match = re.search(r"\d+", text)
    return match.group(0) if match else text.casefold()


def machine_uses_mixed_air_architecture(value: object) -> bool:
    return normalize_machine_number(value) in MIXED_AIR_CLEANROOM_MACHINES


def default_air_architecture_for_machine(value: object) -> str:
    return AIR_ARCHITECTURE_MIXED if machine_uses_mixed_air_architecture(value) else AIR_ARCHITECTURE_ROBOT_ONLY


def air_architecture_hides_external_fields(value: object) -> bool:
    return str(value or "").strip() == AIR_ARCHITECTURE_ROBOT_ONLY


def air_architecture_hides_robot_fields(value: object) -> bool:
    return str(value or "").strip() == AIR_ARCHITECTURE_EXTERNAL_ONLY
