from __future__ import annotations

ENTRY_TYPE_FIELD = "Entry Type"
SOURCE_AUDIT_ID_FIELD = "Source Audit ID"
COMPATIBILITY_SOURCE_FIELD = "Compatibility Source"
AUDIT_CONTEXT_FIELD = "Audit Context"
PHYSICAL_AUDIT_VERIFIED_FIELD = "Physical Audit Verified"
COMPATIBILITY_CONFIDENCE_FIELD = "Compatibility Confidence"

ENTRY_TYPE_AUDITED = "Audited"
ENTRY_TYPE_COMPATIBLE = "Compatible"
COMPATIBILITY_SOURCE_PRESS_CAPACITY = "Press Capacity List"

AUDIT_CONTEXT_INSTALLED = "Installed on Machine"
AUDIT_CONTEXT_BENCH = "Not Installed / Bench Audit"
AUDIT_CONTEXT_COMPATIBILITY = "Compatibility row"
AUDIT_CONTEXT_HISTORICAL = "Historical/imported"
AUDIT_CONTEXT_NEEDS_REVIEW = "Needs review"
AUDIT_CONTEXT_VALUES = [
    AUDIT_CONTEXT_INSTALLED,
    AUDIT_CONTEXT_BENCH,
    AUDIT_CONTEXT_COMPATIBILITY,
    AUDIT_CONTEXT_HISTORICAL,
    AUDIT_CONTEXT_NEEDS_REVIEW,
]

VALIDATION_STATUS_PASS = "Pass"
VALIDATION_STATUS_FAIL = "Fail"
VALIDATION_STATUS_WARNING = "Warning"
VALIDATION_STATUS_UNKNOWN = "Unknown"
VALIDATION_STATUS_NOT_OBSERVABLE = "Not Observable"
VALIDATION_STATUS_NOT_APPLICABLE = "Not Applicable"
VALIDATION_STATUS_FOLLOW_UP_REQUIRED = "Follow-up Required"
VALIDATION_STATUS_VALUES = [
    VALIDATION_STATUS_PASS,
    VALIDATION_STATUS_FAIL,
    VALIDATION_STATUS_WARNING,
    VALIDATION_STATUS_UNKNOWN,
    VALIDATION_STATUS_NOT_OBSERVABLE,
    VALIDATION_STATUS_NOT_APPLICABLE,
    VALIDATION_STATUS_FOLLOW_UP_REQUIRED,
]

CYLINDER_COUNT_FIELD = "# of Cylinders"
CYLINDER_TYPE_FIELD = "Cylinder Type"
CYLINDER_TYPE_DEFAULT = "Linear"
CYLINDER_TYPE_VALUES = ["Linear", "Rotary"]
CYLINDER_FIELDS = frozenset({CYLINDER_COUNT_FIELD, CYLINDER_TYPE_FIELD})

MANUAL_COMPLETION_OVERRIDE_FIELD = "Manual Completion Override"
MANUAL_COMPLETION_OVERRIDE_TIMESTAMP_FIELD = "Manual Completion Override Timestamp"
MANUAL_COMPLETION_OVERRIDE_USER_FIELD = "Manual Completion Override User"
IGNORED_EMPTY_FIELDS_AT_OVERRIDE_FIELD = "Ignored Empty Fields At Override"
MANUAL_COMPLETION_OVERRIDE_FIELDS = [
    MANUAL_COMPLETION_OVERRIDE_FIELD,
    MANUAL_COMPLETION_OVERRIDE_TIMESTAMP_FIELD,
    MANUAL_COMPLETION_OVERRIDE_USER_FIELD,
    IGNORED_EMPTY_FIELDS_AT_OVERRIDE_FIELD,
]

COMPATIBILITY_HEADERS = [
    AUDIT_CONTEXT_FIELD,
    ENTRY_TYPE_FIELD,
    SOURCE_AUDIT_ID_FIELD,
    COMPATIBILITY_SOURCE_FIELD,
    PHYSICAL_AUDIT_VERIFIED_FIELD,
    COMPATIBILITY_CONFIDENCE_FIELD,
]

AUTOFILLED_COMPATIBILITY_METADATA_FIELDS = frozenset(
    {
        SOURCE_AUDIT_ID_FIELD,
        COMPATIBILITY_SOURCE_FIELD,
    }
)
