from __future__ import annotations

ENTRY_TYPE_FIELD = "Entry Type"
SOURCE_AUDIT_ID_FIELD = "Source Audit ID"
COMPATIBILITY_SOURCE_FIELD = "Compatibility Source"

ENTRY_TYPE_AUDITED = "Audited"
ENTRY_TYPE_COMPATIBLE = "Compatible"
COMPATIBILITY_SOURCE_PRESS_CAPACITY = "Press Capacity List"

COMPATIBILITY_HEADERS = [
    ENTRY_TYPE_FIELD,
    SOURCE_AUDIT_ID_FIELD,
    COMPATIBILITY_SOURCE_FIELD,
]
