from __future__ import annotations

from typing import Protocol


class DataGateway(Protocol):
    def get_home_summary(self) -> dict: ...
    def search(self, query: str, filters: dict | None = None) -> list[dict]: ...
    def refresh(self) -> dict: ...
    def deep_refresh(self) -> dict: ...
