"""Export the desktop Minimalist theme as browser CSS and JSON.

Project Mirrorline treats ``app.atlas.minimalist.theme`` as its design-token
authority.  This exporter is deliberately small and deterministic so a web
build can fail when generated browser tokens have drifted from the desktop.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.atlas.minimalist.theme import GLASS_TOKENS, THEME_TOKENS  # noqa: E402

CSS_PATH = ROOT / "web" / "src" / "styles" / "generated-theme-tokens.css"
JSON_PATH = ROOT / "web" / "src" / "styles" / "generated-theme-tokens.json"


def _css_name(name: str) -> str:
    return name.replace("_", "-")


def render_css() -> str:
    lines = [
        "/* Generated by scripts/export_minimalist_theme_tokens.py. Do not edit. */",
        ":root { color-scheme: dark; }",
    ]
    for name in ("dark", "light"):
        tokens = THEME_TOKENS[name].as_dict()
        lines.append(f':root[data-atlas-theme="{name}"] {{')
        for key, value in tokens.items():
            lines.append(f"  --atlas-{_css_name(key)}: {value};")
        for role, values in GLASS_TOKENS[name].items():
            for key, value in values.items():
                lines.append(f"  --atlas-glass-{_css_name(role)}-{_css_name(key)}: {value};")
        lines.append("}")
    return "\n".join(lines) + "\n"


def render_json() -> str:
    payload = {
        "themes": {name: THEME_TOKENS[name].as_dict() for name in ("dark", "light")},
        "glass": {name: GLASS_TOKENS[name] for name in ("dark", "light")},
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    expected = {CSS_PATH: render_css(), JSON_PATH: render_json()}
    stale = [path for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("Minimalist browser theme tokens are stale:")
            print("\n".join(str(path.relative_to(ROOT)) for path in stale))
            return 1
        return 0
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
