[CmdletBinding()]
param(
    [string]$ProjectRoot = "",
    [string]$PythonExe = "",
    [switch]$VerboseLog
)

$ErrorActionPreference = "Stop"

function Get-AppRoot {
    return (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
}

function Get-ConfiguredProjectRoot {
    param([string]$AppRoot, [string]$RequestedProjectRoot)

    if ($RequestedProjectRoot) {
        return (Resolve-Path -LiteralPath $RequestedProjectRoot).Path
    }

    $localConfig = Join-Path $AppRoot "config\local_config.json"
    if (Test-Path -LiteralPath $localConfig) {
        try {
            $config = Get-Content -LiteralPath $localConfig -Raw | ConvertFrom-Json
            if ($config.project_root) {
                return (Resolve-Path -LiteralPath ([string]$config.project_root)).Path
            }
        } catch {
            throw "Could not use local config project_root. Fix config/local_config.json or pass -ProjectRoot. $($_.Exception.Message)"
        }
    }

    return (Resolve-Path -LiteralPath (Join-Path $AppRoot "examples\demo_project")).Path
}

function Write-ScheduledToolLog {
    param([string]$Root, [string]$Line)

    $logDir = Join-Path $Root "00_Project_Admin\logs"
    New-Item -ItemType Directory -Force -Path $logDir | Out-Null
    $logPath = Join-Path $logDir "scheduled_tools.log"
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -LiteralPath $logPath -Value "[$timestamp] $Line"
}

$appRoot = Get-AppRoot
$projectRootResolved = Get-ConfiguredProjectRoot -AppRoot $appRoot -RequestedProjectRoot $ProjectRoot
$python = if ($PythonExe) { $PythonExe } elseif ($env:PYTHON) { $env:PYTHON } else { "python" }
$script = Join-Path $appRoot "daily_status_summary.py"

Set-Location -LiteralPath $appRoot
Write-ScheduledToolLog -Root $projectRootResolved -Line "START daily_summary scheduled=true"

$started = Get-Date
$toolArgs = @(
    $script,
    "--project-root", $projectRootResolved,
    "--scheduled",
    "--completed", "Reviewed EOAT Command Center dashboard status",
    "--need", "Confirm next EOAT project priority with mentor or supervisor",
    "--plan", "Continue EOAT project execution from the current schedule",
    "--note", "Generated by EOAT scheduled summary automation."
)
if ($VerboseLog) {
    $toolArgs += "--verbose"
}

try {
    $output = & $python @toolArgs 2>&1
    $exitCode = if ($LASTEXITCODE -ne $null) { [int]$LASTEXITCODE } else { 0 }
    $outputText = ($output | Out-String).Trim()
    if ($outputText) {
        Write-Output $outputText
    }
    $elapsed = [Math]::Round(((Get-Date) - $started).TotalSeconds, 2)
    if ($exitCode -ne 0) {
        Write-ScheduledToolLog -Root $projectRootResolved -Line "FAILURE daily_summary exit_code=$exitCode elapsed=${elapsed}s error=`"$($outputText -replace '"', "'")`""
        exit $exitCode
    }
    $reportLine = ($output | Where-Object { [string]$_ -match "Created daily status report:|already exists" } | Select-Object -First 1)
    Write-ScheduledToolLog -Root $projectRootResolved -Line "SUCCESS daily_summary output=`"$reportLine`" elapsed=${elapsed}s"
    exit 0
} catch {
    $elapsed = [Math]::Round(((Get-Date) - $started).TotalSeconds, 2)
    Write-ScheduledToolLog -Root $projectRootResolved -Line "FAILURE daily_summary elapsed=${elapsed}s error=`"$($_.Exception.Message -replace '"', "'")`""
    Write-Error $_
    exit 1
}
