from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

TOOLKIT_ROOT = Path(__file__).resolve().parents[1]
if str(TOOLKIT_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLKIT_ROOT))

from core.constants import DEFAULT_PROJECT_ROOT
from core.result import ToolResult
from core.scheduled_reports import (
    DEFAULT_SCHEDULE_TIMEZONE,
    run_daily_summary_now,
    run_due_scheduled_summaries,
    run_weekly_summary_now,
)


def _parse_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    return datetime.fromisoformat(normalized)


def _aggregate(results: list[ToolResult]) -> ToolResult:
    success = all(result.success for result in results)
    return ToolResult(
        tool_id="scheduled_summaries_test",
        tool_name="Scheduled Summaries Test Runner",
        success=success,
        summary="Scheduled summary test run completed." if success else "Scheduled summary test run failed.",
        details=[result.summary for result in results],
        warnings=[warning for result in results for warning in result.warnings],
        errors=[error for result in results for error in result.errors],
        files_created=[path for result in results for path in result.files_created],
        output_reports=[path for result in results for path in result.output_reports],
        metrics={"results": [result.to_dict() for result in results]},
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Safely test EOAT scheduled daily and weekly summaries.")
    parser.add_argument("--project-root", default=str(DEFAULT_PROJECT_ROOT), help="EOAT project root to test against.")
    parser.add_argument("--daily", action="store_true", help="Include the daily summary.")
    parser.add_argument("--weekly", action="store_true", help="Include the weekly summary.")
    parser.add_argument("--dry-run", action="store_true", default=True, help="Write test outputs only. Enabled by default.")
    parser.add_argument("--now", help="Optional fake scheduler datetime, for example 2026-05-25T19:00:00-04:00.")
    parser.add_argument("--timezone", default=DEFAULT_SCHEDULE_TIMEZONE, help="Scheduler timezone. Defaults to America/New_York.")
    parser.add_argument("--force", action="store_true", help="Allow the scheduler harness to run even when the same-date test output exists.")
    parser.add_argument("--verbose", action="store_true", help="Print structured result JSON after the Markdown summary.")
    args = parser.parse_args()

    project_root = Path(args.project_root).expanduser().resolve()
    include_daily = args.daily or not args.weekly
    include_weekly = args.weekly or not args.daily
    fake_now = _parse_datetime(args.now)

    if fake_now is not None:
        result = run_due_scheduled_summaries(
            project_root,
            current_datetime=fake_now,
            timezone_name=args.timezone,
            dry_run=args.dry_run,
            run_daily=include_daily,
            run_weekly=include_weekly,
            force=args.force,
        )
    else:
        results: list[ToolResult] = []
        if include_daily:
            results.append(run_daily_summary_now(project_root, dry_run=args.dry_run, mode="manual_test", decision_reason="manual daily summary test run"))
        if include_weekly:
            results.append(
                run_weekly_summary_now(
                    project_root,
                    dry_run=args.dry_run,
                    notes="Generated by EOAT manual automation dry-run test.",
                    mode="manual_test",
                    decision_reason="manual weekly summary test run",
                )
            )
        result = _aggregate(results)

    print(result.to_markdown())
    if args.verbose:
        print(json.dumps(result.to_dict(), indent=2))
    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
