"""initial_mysql_schema

Revision ID: 20260713_0001
Revises: 
Create Date: 2026-07-13 16:28:59.054367
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '20260713_0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_statuses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cleanroom_classifications',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('compatibility_sources',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('compatibility_statuses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('connection_types',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_types',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('eoat_types',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('history_event_types',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('import_batches',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('batch_name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_file_name', sa.String(length=512), nullable=False),
    sa.Column('source_file_checksum', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('records_discovered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_imported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_rejected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warnings_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_uuid')
    )
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('system_metadata',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('metadata_key', sa.String(length=128), nullable=False),
    sa.Column('metadata_value', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metadata_key')
    )
    op.create_table('import_rows',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('target_entity_type', sa.String(length=64), nullable=True),
    sa.Column('target_entity_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_values_json', sa.JSON(), nullable=True),
    sa.Column('normalized_values_json', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_batch_id', 'source_sheet', 'source_row_number', name='uq_import_rows_source')
    )
    op.create_index('ix_import_rows_target', 'import_rows', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('external_identity', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('authentication_provider', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_identity'),
    sa.UniqueConstraint('username')
    )
    op.create_table('change_feed',
    sa.Column('change_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('entity_row_version', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('changed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index('ix_change_feed_changed', 'change_feed', ['changed_at'], unique=False)
    op.create_index('ix_change_feed_entity_cursor', 'change_feed', ['entity_type', 'change_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('document_uuid', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_extension', sa.String(length=32), nullable=True),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('storage_provider', sa.String(length=64), server_default=sa.text("'network_file'"), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_document_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_uuid')
    )
    op.create_index('ix_documents_checksum', 'documents', ['checksum_sha256'], unique=False)
    op.create_index('ix_documents_number', 'documents', ['document_number'], unique=False)
    op.create_table('eoats',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('business_identifier', sa.String(length=64), nullable=False),
    sa.Column('legacy_identifier', sa.String(length=96), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eoat_type_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('connection_type_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('cleanroom_classification_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('number_of_parts_picked', sa.Integer(), nullable=True),
    sa.Column('number_of_vacuum_cups', sa.Integer(), nullable=True),
    sa.Column('number_of_grippers', sa.Integer(), nullable=True),
    sa.Column('vacuum_present', sa.Boolean(), nullable=True),
    sa.Column('sensors_present', sa.Boolean(), nullable=True),
    sa.Column('part_present_sensor_present', sa.Boolean(), nullable=True),
    sa.Column('vacuum_confirmation_sensor_present', sa.Boolean(), nullable=True),
    sa.Column('quick_disconnect_present', sa.Boolean(), nullable=True),
    sa.Column('cup_material', sa.String(length=160), nullable=True),
    sa.Column('frame_material', sa.String(length=160), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('maximum_payload_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('drawing_number', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('date_built', sa.Date(), nullable=True),
    sa.Column('date_commissioned', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('number_of_grippers IS NULL OR number_of_grippers >= 0', name='ck_eoats_grippers_nonnegative'),
    sa.CheckConstraint('number_of_parts_picked IS NULL OR number_of_parts_picked >= 0', name='ck_eoats_parts_nonnegative'),
    sa.CheckConstraint('number_of_vacuum_cups IS NULL OR number_of_vacuum_cups >= 0', name='ck_eoats_cups_nonnegative'),
    sa.CheckConstraint('row_version > 0', name='ck_eoats_row_version'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cleanroom_classification_id'], ['cleanroom_classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_type_id'], ['connection_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_type_id'], ['eoat_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_identifier')
    )
    op.create_index('ix_eoats_display_name', 'eoats', ['display_name'], unique=False)
    op.create_index('ix_eoats_legacy_identifier', 'eoats', ['legacy_identifier'], unique=False)
    op.create_table('import_issues',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('import_row_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('source_value', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_issues_batch_severity', 'import_issues', ['import_batch_id', 'severity'], unique=False)
    op.create_table('parts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(length=96), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('part_family', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=160), nullable=True),
    sa.Column('material', sa.String(length=160), nullable=True),
    sa.Column('resin_type', sa.String(length=160), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('cleanroom_required', sa.Boolean(), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_index('ix_parts_family', 'parts', ['part_family'], unique=False)
    op.create_index('ix_parts_name', 'parts', ['part_name'], unique=False)
    op.create_table('plants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plant_code', sa.String(length=32), nullable=False),
    sa.Column('plant_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('row_version > 0', name='ck_plants_row_version'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_code')
    )
    op.create_table('system_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('setting_value_json', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('tools',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('business_identifier', sa.String(length=96), nullable=False),
    sa.Column('tool_number', sa.String(length=96), nullable=True),
    sa.Column('mold_number', sa.String(length=96), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cavity_count', sa.Integer(), nullable=True),
    sa.Column('tool_type', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=160), nullable=True),
    sa.Column('program_name', sa.String(length=160), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_identifier')
    )
    op.create_index('ix_tools_mold_number', 'tools', ['mold_number'], unique=False)
    op.create_index('ix_tools_tool_number', 'tools', ['tool_number'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('assigned_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'assigned_at', name='uq_user_roles_assignment')
    )
    op.create_table('areas',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('area_code', sa.String(length=64), nullable=False),
    sa.Column('area_name', sa.String(length=160), nullable=False),
    sa.Column('area_type', sa.String(length=64), nullable=True),
    sa.Column('cleanroom_classification_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cleanroom_classification_id'], ['cleanroom_classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'area_code', name='uq_areas_plant_code')
    )
    op.create_table('document_links',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entity_type', 'entity_id', 'relationship_type', name='uq_document_links')
    )
    op.create_index('ix_document_links_entity', 'document_links', ['entity_type', 'entity_id'], unique=False)
    op.create_table('eoat_tool_compatibility',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('part_geometry_compatible', sa.Boolean(), nullable=True),
    sa.Column('number_of_parts_compatible', sa.Boolean(), nullable=True),
    sa.Column('vacuum_or_gripper_compatible', sa.Boolean(), nullable=True),
    sa.Column('sensor_compatible', sa.Boolean(), nullable=True),
    sa.Column('cycle_requirement_compatible', sa.Boolean(), nullable=True),
    sa.Column('compatibility_status_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('verification_source_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_eoat_tool_compatibility_dates'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compatibility_status_id'], ['compatibility_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_source_id'], ['compatibility_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eoat_id', 'tool_id', 'effective_from', name='uq_eoat_tool_compatibility_effective')
    )
    op.create_index('ix_eoat_tool_lookup', 'eoat_tool_compatibility', ['eoat_id', 'tool_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('photo_view_type', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_profile_photo', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('width_pixels', sa.Integer(), nullable=True),
    sa.Column('height_pixels', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('tool_parts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('part_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('is_primary_part', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_tool_parts_dates'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'part_id', 'effective_from', name='uq_tool_parts_effective')
    )
    op.create_table('application_instances',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('instance_uuid', sa.String(length=36), nullable=False),
    sa.Column('computer_name', sa.String(length=255), nullable=False),
    sa.Column('installation_name', sa.String(length=160), nullable=True),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('area_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('application_version', sa.String(length=64), nullable=False),
    sa.Column('launcher_version', sa.String(length=64), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_uuid')
    )
    op.create_table('machines',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('area_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('machine_number', sa.String(length=64), nullable=False),
    sa.Column('machine_name', sa.String(length=160), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('machine_type', sa.String(length=64), nullable=True),
    sa.Column('press_capacity_tons', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('controller_type', sa.String(length=160), nullable=True),
    sa.Column('cleanroom_classification_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('press_capacity_tons IS NULL OR press_capacity_tons > 0', name='ck_machines_capacity_positive'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cleanroom_classification_id'], ['cleanroom_classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'machine_number', name='uq_machines_plant_number')
    )
    op.create_index('ix_machines_area', 'machines', ['area_id'], unique=False)
    op.create_index('ix_machines_number', 'machines', ['machine_number'], unique=False)
    op.create_table('robots',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('area_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('robot_number', sa.String(length=64), nullable=False),
    sa.Column('robot_name', sa.String(length=160), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('controller_model', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('payload_capacity_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('reach_mm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mounting_type', sa.String(length=128), nullable=True),
    sa.Column('communication_interface', sa.String(length=128), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('payload_capacity_kg IS NULL OR payload_capacity_kg > 0', name='ck_robots_payload_positive'),
    sa.CheckConstraint('reach_mm IS NULL OR reach_mm > 0', name='ck_robots_reach_positive'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'robot_number', name='uq_robots_plant_number')
    )
    op.create_index('ix_robots_number', 'robots', ['robot_number'], unique=False)
    op.create_table('storage_locations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('area_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('location_code', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'location_code', name='uq_storage_locations_plant_code')
    )
    op.create_table('audit_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('audit_identifier', sa.String(length=96), nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('robot_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('audit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_sheet', sa.String(length=128), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_identifier')
    )
    op.create_index('ix_audit_records_date', 'audit_records', ['audit_date'], unique=False)
    op.create_index('ix_audit_records_entities', 'audit_records', ['eoat_id', 'machine_id', 'tool_id'], unique=False)
    op.create_table('change_audit_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('event_uuid', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('application_instance_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_values_json', sa.JSON(), nullable=True),
    sa.Column('new_values_json', sa.JSON(), nullable=True),
    sa.Column('changed_fields_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('api_version', sa.String(length=64), nullable=True),
    sa.Column('client_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_instance_id'], ['application_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid')
    )
    op.create_index('ix_change_audit_actor', 'change_audit_log', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_change_audit_entity', 'change_audit_log', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index('ix_change_audit_request', 'change_audit_log', ['request_id'], unique=False)
    op.create_table('entity_history_events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_type_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('application_instance_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_table', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_instance_id'], ['application_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_type_id'], ['history_event_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_history_timeline', 'entity_history_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('eoat_installations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('robot_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('installation_reason', sa.String(length=255), nullable=True),
    sa.Column('removal_reason', sa.String(length=255), nullable=True),
    sa.Column('installation_notes', sa.Text(), nullable=True),
    sa.Column('removal_notes', sa.Text(), nullable=True),
    sa.Column('application_instance_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('active_eoat_marker', mysql.BIGINT(unsigned=True), sa.Computed('CASE WHEN removed_at IS NULL THEN eoat_id ELSE NULL END', ), nullable=True),
    sa.Column('active_machine_marker', mysql.BIGINT(unsigned=True), sa.Computed('CASE WHEN removed_at IS NULL THEN machine_id ELSE NULL END', ), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('removed_at IS NULL OR removed_at >= installed_at', name='ck_eoat_installations_dates'),
    sa.ForeignKeyConstraint(['application_instance_id'], ['application_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_eoat_marker', name='uq_active_installation_eoat'),
    sa.UniqueConstraint('active_machine_marker', name='uq_active_installation_machine')
    )
    op.create_index('ix_installations_eoat_started', 'eoat_installations', ['eoat_id', 'installed_at'], unique=False)
    op.create_index('ix_installations_machine_started', 'eoat_installations', ['machine_id', 'installed_at'], unique=False)
    op.create_index('ix_installations_removed', 'eoat_installations', ['removed_at'], unique=False)
    op.create_table('eoat_machine_compatibility',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('connection_compatible', sa.Boolean(), nullable=True),
    sa.Column('payload_compatible', sa.Boolean(), nullable=True),
    sa.Column('reach_compatible', sa.Boolean(), nullable=True),
    sa.Column('cleanroom_compatible', sa.Boolean(), nullable=True),
    sa.Column('robot_interface_compatible', sa.Boolean(), nullable=True),
    sa.Column('utilities_compatible', sa.Boolean(), nullable=True),
    sa.Column('compatibility_status_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('verification_source_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_eoat_machine_compatibility_dates'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compatibility_status_id'], ['compatibility_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_source_id'], ['compatibility_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eoat_id', 'machine_id', 'effective_from', name='uq_eoat_machine_compatibility_effective')
    )
    op.create_index('ix_eoat_machine_lookup', 'eoat_machine_compatibility', ['eoat_id', 'machine_id'], unique=False)
    op.create_index('ix_machine_compatibility_status', 'eoat_machine_compatibility', ['machine_id', 'compatibility_status_id'], unique=False)
    op.create_table('eoat_storage_assignments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('storage_location_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_from_storage_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('removed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('active_eoat_marker', mysql.BIGINT(unsigned=True), sa.Computed('CASE WHEN removed_from_storage_at IS NULL THEN eoat_id ELSE NULL END', ), nullable=True),
    sa.CheckConstraint('removed_from_storage_at IS NULL OR removed_from_storage_at >= stored_at', name='ck_eoat_storage_dates'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stored_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_eoat_marker', name='uq_active_storage_eoat')
    )
    op.create_table('fit_check_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('eoat_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('overall_status_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('machine_tool_status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('machine_eoat_status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('tool_eoat_status_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('evaluation_engine_version', sa.String(length=64), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('performed_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('application_instance_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('result_details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.ForeignKeyConstraint(['application_instance_id'], ['application_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eoat_id'], ['eoats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_eoat_status_id'], ['compatibility_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_tool_status_id'], ['compatibility_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['overall_status_id'], ['compatibility_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_eoat_status_id'], ['compatibility_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fit_checks_entities', 'fit_check_records', ['machine_id', 'tool_id', 'eoat_id'], unique=False)
    op.create_index('ix_fit_checks_performed', 'fit_check_records', ['performed_at'], unique=False)
    op.create_table('machine_robot_assignments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('robot_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.CheckConstraint('removed_at IS NULL OR removed_at >= assigned_at', name='ck_machine_robot_dates'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machine_robot_active', 'machine_robot_assignments', ['machine_id', 'removed_at'], unique=False)
    op.create_table('tool_machine_compatibility',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tool_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('machine_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tonnage_compatible', sa.Boolean(), nullable=True),
    sa.Column('physical_size_compatible', sa.Boolean(), nullable=True),
    sa.Column('utilities_compatible', sa.Boolean(), nullable=True),
    sa.Column('process_compatible', sa.Boolean(), nullable=True),
    sa.Column('compatibility_status_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('verification_source_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default=sa.text("'eoat_atlas'"), nullable=False),
    sa.Column('source_import_batch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(UTC_TIMESTAMP(6))'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_tool_machine_compatibility_dates'),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compatibility_status_id'], ['compatibility_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_source_id'], ['compatibility_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'machine_id', 'effective_from', name='uq_tool_machine_compatibility_effective')
    )
    op.create_index('ix_tool_machine_lookup', 'tool_machine_compatibility', ['tool_id', 'machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_machine_lookup', table_name='tool_machine_compatibility')
    op.drop_table('tool_machine_compatibility')
    op.drop_index('ix_machine_robot_active', table_name='machine_robot_assignments')
    op.drop_table('machine_robot_assignments')
    op.drop_index('ix_fit_checks_performed', table_name='fit_check_records')
    op.drop_index('ix_fit_checks_entities', table_name='fit_check_records')
    op.drop_table('fit_check_records')
    op.drop_table('eoat_storage_assignments')
    op.drop_index('ix_machine_compatibility_status', table_name='eoat_machine_compatibility')
    op.drop_index('ix_eoat_machine_lookup', table_name='eoat_machine_compatibility')
    op.drop_table('eoat_machine_compatibility')
    op.drop_index('ix_installations_removed', table_name='eoat_installations')
    op.drop_index('ix_installations_machine_started', table_name='eoat_installations')
    op.drop_index('ix_installations_eoat_started', table_name='eoat_installations')
    op.drop_table('eoat_installations')
    op.drop_index('ix_entity_history_timeline', table_name='entity_history_events')
    op.drop_table('entity_history_events')
    op.drop_index('ix_change_audit_request', table_name='change_audit_log')
    op.drop_index('ix_change_audit_entity', table_name='change_audit_log')
    op.drop_index('ix_change_audit_actor', table_name='change_audit_log')
    op.drop_table('change_audit_log')
    op.drop_index('ix_audit_records_entities', table_name='audit_records')
    op.drop_index('ix_audit_records_date', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_table('storage_locations')
    op.drop_index('ix_robots_number', table_name='robots')
    op.drop_table('robots')
    op.drop_index('ix_machines_number', table_name='machines')
    op.drop_index('ix_machines_area', table_name='machines')
    op.drop_table('machines')
    op.drop_table('application_instances')
    op.drop_table('tool_parts')
    op.drop_table('photos')
    op.drop_index('ix_eoat_tool_lookup', table_name='eoat_tool_compatibility')
    op.drop_table('eoat_tool_compatibility')
    op.drop_index('ix_document_links_entity', table_name='document_links')
    op.drop_table('document_links')
    op.drop_table('areas')
    op.drop_table('user_roles')
    op.drop_index('ix_tools_tool_number', table_name='tools')
    op.drop_index('ix_tools_mold_number', table_name='tools')
    op.drop_table('tools')
    op.drop_table('system_settings')
    op.drop_table('plants')
    op.drop_index('ix_parts_name', table_name='parts')
    op.drop_index('ix_parts_family', table_name='parts')
    op.drop_table('parts')
    op.drop_index('ix_import_issues_batch_severity', table_name='import_issues')
    op.drop_table('import_issues')
    op.drop_index('ix_eoats_legacy_identifier', table_name='eoats')
    op.drop_index('ix_eoats_display_name', table_name='eoats')
    op.drop_table('eoats')
    op.drop_index('ix_documents_number', table_name='documents')
    op.drop_index('ix_documents_checksum', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_change_feed_entity_cursor', table_name='change_feed')
    op.drop_index('ix_change_feed_changed', table_name='change_feed')
    op.drop_table('change_feed')
    op.drop_table('users')
    op.drop_index('ix_import_rows_target', table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_table('system_metadata')
    op.drop_table('roles')
    op.drop_table('import_batches')
    op.drop_table('history_event_types')
    op.drop_table('eoat_types')
    op.drop_table('document_types')
    op.drop_table('connection_types')
    op.drop_table('compatibility_statuses')
    op.drop_table('compatibility_sources')
    op.drop_table('cleanroom_classifications')
    op.drop_table('asset_statuses')
    # ### end Alembic commands ###

